apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::156719884113:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QROKZ1CQJSDF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::156719884113:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-04T01:03:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1625"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 597f88e2-7c85-4e08-a329-6edb621525f7
